"""Add login_client to login_gov_state

Revision ID: 8d2f4c6a1b3e
Revises: 0c0638b3010e
Create Date: 2026-10-07 05:40:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d2f4c6a1b3e"
down_revision = "0c0638b3010e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login_gov_state",
        sa.Column("login_client", sa.Text(), nullable=True),
        schema="api",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login_gov_state", "login_client", schema="api")
    # ### end Alembic commands ###
